# Generated by Django 4.2.23 on 2025-06-24 13:24

from django.db import migrations, models
import django.db.models.deletion
import user_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID utente collegato ad auth_service', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Nome dell'utente", max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(help_text="Cognome dell'utente", max_length=150, verbose_name='Cognome')),
                ('display_name', models.CharField(blank=True, help_text='Nome pubblico visualizzato (opzionale)', max_length=100, null=True, verbose_name='Nome visualizzato')),
                ('email', models.EmailField(blank=True, help_text="Indirizzo email dell'utente", max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Numero di telefono in formato internazionale (es. +39...)', max_length=20, null=True, validators=[user_api.models.validate_phone_number], verbose_name='Numero di telefono')),
                ('profile_picture_url', models.CharField(blank=True, help_text="URL o path dell'immagine del profilo", max_length=500, null=True, verbose_name='URL immagine profilo')),
                ('bio', models.TextField(blank=True, help_text="Breve descrizione dell'utente (max 500 caratteri)", max_length=500, null=True, verbose_name='Biografia')),
                ('location', models.CharField(blank=True, help_text='Città o località dell\'utente (es. "Bologna, Italia")', max_length=100, null=True, verbose_name='Località')),
                ('date_of_birth', models.DateField(blank=True, help_text="Data di nascita dell'utente", null=True, verbose_name='Data di nascita')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text="Preferenze e impostazioni personalizzate dell'utente", verbose_name='Preferenze')),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('inactive', 'Inattivo'), ('suspended', 'Sospeso'), ('pending', 'In attesa')], default='active', help_text="Stato corrente dell'account utente", max_length=20, verbose_name='Stato')),
                ('last_activity', models.DateTimeField(blank=True, help_text="Timestamp dell'ultima attività dell'utente", null=True, verbose_name='Ultima attività')),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utente',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_profil_email_8a1024_idx'), models.Index(fields=['status'], name='user_profil_status_6d69fb_idx'), models.Index(fields=['last_activity'], name='user_profil_last_ac_ae158c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('profile_update', 'Aggiornamento profilo'), ('preference_update', 'Aggiornamento preferenze'), ('avatar_upload', 'Caricamento avatar'), ('login', 'Accesso'), ('logout', 'Disconnessione')], max_length=50, verbose_name='Azione')),
                ('description', models.TextField(blank=True, help_text="Descrizione dettagliata dell'azione", verbose_name='Descrizione')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Dati aggiuntivi relativi all'azione", verbose_name='Metadati')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='user_api.userprofile', verbose_name='Profilo utente')),
            ],
            options={
                'verbose_name': 'Log Attività Utente',
                'verbose_name_plural': 'Log Attività Utenti',
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', '-created_at'], name='user_activi_user_pr_eb5af3_idx'), models.Index(fields=['action'], name='user_activi_action_7f2936_idx')],
            },
        ),
    ]
