# Generated by Django 4.2.23 on 2025-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text="Indica se l'utente ha completato il processo di onboarding", verbose_name='Registrazione completata'),
        ),
    ]
