# Generated by Django 4.2.23 on 2025-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_add_registration_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, help_text='Nome utente univoco', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
