services:
  # Override NGINX service to use local configuration without SSL
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - media_images:/media_images
      - media_resources:/media_resources  
      - media_analysis_results:/media_analysis_results
      - media_users:/media_users
      - media_rag_uploads:/media_rag_uploads
    depends_on:
      - frontend
      - auth_service
      - user_service
      - chatbot_service
      - image_generator_service
      - resource_manager_service
      - image_classifier_service
      - data_analysis_service
      - rag_service
      - learning_service
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  media_images:
  media_resources:
  media_analysis_results:
  media_users:
  media_rag_uploads:

networks:
  app_network:
    driver: bridge 