#!/bin/bash

# =============================================================================
# Script Setup Environment per AI-PlayGround
# Configura automaticamente file .env e secrets
# =============================================================================

set -e

# Colori per output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

# Banner
echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║               AI-PLAYGROUND ENVIRONMENT SETUP               ║"
echo "║                Configurazione Automatica                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Funzioni utility
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Funzione per generare password sicure
generate_password() {
    local length=${1:-32}
    openssl rand -base64 $length | tr -d "=+/" | cut -c1-$length
}

# Funzione per generare Django secret key (solo caratteri sicuri per sed)
generate_django_secret() {
    # Genera 50 caratteri alfanumerici sicuri (no caratteri speciali per sed)
    openssl rand -hex 25 | head -c 50
}

# Verifica prerequisiti
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v openssl &> /dev/null; then
        log_error "OpenSSL is required but not installed."
        exit 1
    fi
    
    log_success "Prerequisites check passed"
}

# Crea file .env.dev
create_env_dev_file() {
    cat > .env.dev << 'EOF'
# =============================================================================
# AI-PLAYGROUND DEVELOPMENT ENVIRONMENT
# File: .env.dev - Generated by setup-env.sh
# =============================================================================

# =============================================================================
# GENERAL DJANGO SETTINGS
# =============================================================================
DJANGO_DEBUG=True
DJANGO_SECRET_KEY=dev-secret-key-x8k3m7p2q5w9r6t4y7u0i3o6p9a2s5d8f1g4h7j0k3l6z9x2c5v8b
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,dev.pl-ai.it,frontend,auth_service,user_service,chatbot_service,rag_service,llm_service,image_generator_service,data_analysis_service,resource_manager_service,image_classifier_service,learning_service,cost_monitoring_service
DJANGO_LOG_LEVEL=INFO

# =============================================================================
# DATABASE CONFIGURATION - DEVELOPMENT
# =============================================================================

# Auth Database
AUTH_DB_NAME=auth_db
AUTH_DB_USER=admin
AUTH_DB_PASSWORD=DevAuth2024!K7mN9pQ3xR8vW2sE
DATABASE_URL=postgres://admin:DevAuth2024!K7mN9pQ3xR8vW2sE@auth_db:5432/auth_db

# User Database 
USER_DB_NAME=user_db
USER_DB_USER=admin
USER_DB_PASSWORD=DevUser2024!A4hT6uY9oP1zM5kL
USER_DB_HOST=user_db
USER_DB_PORT=5432

# Chatbot Database
CHATBOT_DB_NAME=chatbot_db
CHATBOT_DB_USER=admin
CHATBOT_DB_PASSWORD=DevChatbot2024!D3fG7jH2nB9vC6xZ
CHATBOT_DB_HOST=chatbot_db
CHATBOT_DB_PORT=5432

# Image Generator Database
IMAGEGEN_DB_NAME=imagegen_db
IMAGEGEN_DB_USER=admin
IMAGEGEN_DB_PASSWORD=DevImageGen2024!X8kM4pW7qR3tY5uI
IMAGE_GEN_DB_NAME=imagegen_db
IMAGE_GEN_DB_USER=admin
IMAGE_GEN_DB_PASSWORD=DevImageGen2024!X8kM4pW7qR3tY5uI
IMAGE_GEN_DB_HOST=image_generator_db
IMAGE_GEN_DB_PORT=5432

# Resource Manager Database
RESOURCE_DB_NAME=resource_db
RESOURCE_DB_USER=admin
RESOURCE_DB_PASSWORD=DevResource2024!V2sF9hJ6mK1nL8pQ
RESOURCE_DB_HOST=resource_db
RESOURCE_DB_PORT=5432

# Classifier Database
CLASSIFIER_DB_NAME=classifier_db
CLASSIFIER_DB_USER=admin
CLASSIFIER_DB_PASSWORD=DevClassifier2024!Z5xC8vB3nM6kH9jG
CLASSIFIER_DB_HOST=classifier_db
CLASSIFIER_DB_PORT=5432

# Analysis Database
ANALYSIS_DB_NAME=analysis_db
ANALYSIS_DB_USER=admin
ANALYSIS_DB_PASSWORD=DevAnalysis2024!T4yU7iO0pA3sD6fG
ANALYSIS_DB_HOST=analysis_db
ANALYSIS_DB_PORT=5432

# RAG Database
RAG_DB_NAME=rag_db
RAG_DB_USER=admin
RAG_DB_PASSWORD=DevRag2024!H9jK2lZ5xC8vB1nM
RAG_DB_HOST=rag_db
RAG_DB_PORT=5432

# Learning Database
LEARNING_DB_NAME=learning_db
LEARNING_DB_USER=admin
LEARNING_DB_PASSWORD=DevLearning2024!Q6wE9rT2yU5iO8pA
SERVICE_DB_NAME=learning_db
SERVICE_DB_USER=admin
SERVICE_DB_PASSWORD=DevLearning2024!Q6wE9rT2yU5iO8pA
SERVICE_DB_HOST=learning_db
SERVICE_DB_PORT=5432

# LLM Service Database
LLM_DB_NAME=llm_service_db
LLM_DB_USER=admin
LLM_DB_PASSWORD=DevLLM2024!Q6wE9rT2yU5iO8pA
LLM_DB_HOST=llm_service_db
LLM_DB_PORT=5432

# Cost Monitoring Database
COST_MONITORING_DB_NAME=cost_monitoring_db
COST_MONITORING_DB_USER=admin
COST_MONITORING_DB_PASSWORD=DevCost2024!Q6wE9rT2yU5iO8pA
COST_DB_HOST=cost_monitoring_db
COST_DB_PORT=5432

# =============================================================================
# RABBITMQ & CELERY CONFIGURATION
# =============================================================================
RABBITMQ_DEFAULT_USER=admin
RABBITMQ_DEFAULT_PASS=DevRabbitMQ2024!S3dF6gH9jK2lZ5xC
CELERY_BROKER_URL=amqp://admin:DevRabbitMQ2024!S3dF6gH9jK2lZ5xC@rabbitmq:5672//

# =============================================================================
# REDIS CONFIGURATION
# =============================================================================
REDIS_URL=redis://redis:6379/1

# =============================================================================
# AUTHENTICATION & JWT CONFIGURATION
# =============================================================================
JWT_SECRET_KEY=dev-jwt-secret-shared-between-services-2024
ACCESS_TOKEN_LIFETIME_DAYS=7
REFRESH_TOKEN_LIFETIME_DAYS=30
INTERNAL_API_SECRET=dev-internal-api-secret-2024-shared

# =============================================================================
# SOCIAL AUTH CONFIGURATION - DEVELOPMENT
# =============================================================================
SOCIAL_AUTH_GOOGLE_ENABLED=true
SOCIAL_AUTH_GOOGLE_CLIENT_ID=876325805414-o2uroeic6t6alt9cuauk4nojh7n1mt55.apps.googleusercontent.com
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET=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

SOCIAL_AUTH_APPLE_ENABLED=false
SOCIAL_AUTH_APPLE_CLIENT_ID=your.apple.client.id
SOCIAL_AUTH_APPLE_TEAM_ID=your-apple-team-id
SOCIAL_AUTH_APPLE_KEY_ID=your-apple-key-id
SOCIAL_AUTH_APPLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nyour-apple-private-key\n-----END PRIVATE KEY-----

SOCIAL_AUTH_GITHUB_ENABLED=false
SOCIAL_AUTH_GITHUB_CLIENT_ID=your-github-client-id
SOCIAL_AUTH_GITHUB_CLIENT_SECRET=your-github-client-secret

# =============================================================================
# SUPABASE CONFIGURATION - DEVELOPMENT
# =============================================================================
SUPABASE_URL=https://vlhruuvlnupusahxlsjq.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaHJ1dXZsbnVwdXNhaHhsc2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzE4NDEsImV4cCI6MjA2Njg0Nzg0MX0.opJ2mUBAfnVqS5ZSR02MhULeywCchV1yRZ9xa0gCHjo
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaHJ1dXZsbnVwdXNhaHhsc2pxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTI3MTg0MSwiZXhwIjoyMDY2ODQ3ODQxfQ.jC5xqbJ4Ds5deF-Vgxjv1QJqz1ey-ecYggxQSMjXWWE
SUPABASE_JWT_SECRET=jUj/DOzLViwMZZhRFD1yEshYAsfhxW0xSmhbGkjTme3tPa0ba+Xor73RwyUt6KqBKlMi7ODXEv73zu3i67MdBA==

# =============================================================================
# RAG SERVICE CONFIGURATION
# =============================================================================
RAG_UPLOADS_ROOT=/app/rag_uploads
RAG_EMBEDDINGS_ROOT=/app/rag_embeddings
RAG_MAX_CHUNK_SIZE=1000
RAG_CHUNK_OVERLAP=200
RAG_TOP_K_RESULTS=5
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_DIMENSION=1536

# =============================================================================
# LLM SERVICE CONFIGURATION
# =============================================================================
OLLAMA_API_BASE_URL=http://ollama_server:11434

# =============================================================================
# LEARNING SERVICE CONFIGURATION
# =============================================================================
DEFAULT_LESSON_LENGTH=15
DEFAULT_QUIZ_QUESTIONS=5
MAX_LESSON_APPROFONDIMENTI=4
OPENAI_API_KEY_FILE=/run/secrets/openai_api_key_secret

# =============================================================================
# COST MONITORING CONFIGURATION
# =============================================================================
COST_MONITORING_SERVICE_URL=http://cost_monitoring_service:8000
EUROS_TO_CREDITS_RATIO=1000
DEFAULT_USER_CREDITS=10000
OPENAI_BASE_URL=https://api.openai.com/v1

# =============================================================================
# FILE UPLOAD CONFIGURATION
# =============================================================================
FILE_UPLOAD_MAX_MEMORY_SIZE=10485760
DATA_UPLOAD_MAX_MEMORY_SIZE=10485760
MAX_PROFILE_PICTURE_SIZE=5242880
ALLOWED_IMAGE_FORMATS=jpg,jpeg,png,gif

# =============================================================================
# USER SERVICE CONFIGURATION
# =============================================================================
DEFAULT_USER_STATUS=active

# =============================================================================
# TENSORFLOW CONFIGURATION
# =============================================================================
TF_CPP_MIN_LOG_LEVEL=2

# =============================================================================
# INTERNAL SERVICE URLS
# =============================================================================
RESOURCE_MANAGER_INTERNAL_URL=http://resource_manager_service:8000
RAG_SERVICE_URL=http://rag_service:8000

# =============================================================================
# STORAGE CONFIGURATION (S3 - Development)
# =============================================================================
USE_S3_STORAGE=false
AWS_ACCESS_KEY_ID=your_aws_access_key_id
AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
AWS_STORAGE_BUCKET_NAME=your_s3_bucket_name
AWS_S3_REGION_NAME=eu-west-1
AWS_S3_CUSTOM_DOMAIN=your_s3_bucket_name.s3.amazonaws.com
AWS_S3_OBJECT_PARAMETERS={"CacheControl": "max-age=86400"}
AWS_DEFAULT_ACL=private

# =============================================================================
# MEDIA & STATIC FILES
# =============================================================================
MEDIA_URL=/media/
STATIC_URL=/static/

# =============================================================================
# DOMAIN CONFIGURATION
# =============================================================================
DOMAIN=dev.pl-ai.it
FRONTEND_URL=https://dev.pl-ai.it
BACKEND_URL=https://dev.pl-ai.it/api
FRONTEND_BASE_URL=https://dev.pl-ai.it

# =============================================================================
# CORS SETTINGS (Development)
# =============================================================================
CORS_ALLOWED_ORIGINS=http://localhost:3000,https://dev.pl-ai.it,http://127.0.0.1:3000,http://localhost:8080,http://127.0.0.1:8080
CORS_ALLOW_CREDENTIALS=true

# =============================================================================
# SSL CONFIGURATION
# =============================================================================
LETSENCRYPT_EMAIL=admin@pl-ai.it
SSL_POLICY=Mozilla-Modern

# =============================================================================
# SECURITY SETTINGS (Development)
# =============================================================================
SECURE_SSL_REDIRECT=false
SECURE_HSTS_SECONDS=0
EOF
}

# Crea file .env.prod
create_env_prod_file() {
    cat > .env.prod << 'EOF'
# =============================================================================
# AI-PLAYGROUND PRODUCTION ENVIRONMENT  
# File: .env.prod - Generated by setup-env.sh
# =============================================================================

# =============================================================================
# GENERAL DJANGO SETTINGS
# =============================================================================
DJANGO_DEBUG=false
DJANGO_SECRET_KEY=prod-ultra-secure-key-n8m2k5j9h6g3f0d1s4a7p0q9w8e5r2t7y4u1i6o3p9a8s5d2f7g0h3j6k9l2z5x8c1v4b
DJANGO_ALLOWED_HOSTS=pl-ai.it,www.pl-ai.it,frontend,auth_service,user_service,chatbot_service,rag_service,llm_service,image_generator_service,data_analysis_service,resource_manager_service,image_classifier_service,learning_service,cost_monitoring_service
DJANGO_LOG_LEVEL=WARNING

# =============================================================================
# DATABASE CONFIGURATION - PRODUCTION
# =============================================================================

# Auth Database
AUTH_DB_NAME=auth_db_prod
AUTH_DB_USER=auth_admin
AUTH_DB_PASSWORD=ProdAuth2024#Kx9Mn7Pq5Xr2Wv8Sg4Tl6Yh1Uj3Zn
DATABASE_URL=postgres://auth_admin:ProdAuth2024#Kx9Mn7Pq5Xr2Wv8Sg4Tl6Yh1Uj3Zn@auth_db:5432/auth_db_prod

# User Database
USER_DB_NAME=user_db_prod  
USER_DB_USER=user_admin
USER_DB_PASSWORD=ProdUser2024#Az8Ht4Uy7Op9Zm1Lk5Pg3Qw6Vb2Nx
USER_DB_HOST=user_db
USER_DB_PORT=5432

# Chatbot Database
CHATBOT_DB_NAME=chatbot_db_prod
CHATBOT_DB_USER=chatbot_admin
CHATBOT_DB_PASSWORD=ProdChatbot2024#Df1Gj5Hm8Nb7Vx3Zc9Kw2Qt6Yr4Eu
CHATBOT_DB_HOST=chatbot_db
CHATBOT_DB_PORT=5432

# Image Generator Database
IMAGEGEN_DB_NAME=imagegen_db_prod
IMAGEGEN_DB_USER=imagegen_admin
IMAGEGEN_DB_PASSWORD=ProdImageGen2024#Xk3Mp8Wq5Rt7Yu2Io9Ap6Sd1Fg4Hj
IMAGE_GEN_DB_NAME=imagegen_db_prod
IMAGE_GEN_DB_USER=imagegen_admin
IMAGE_GEN_DB_PASSWORD=ProdImageGen2024#Xk3Mp8Wq5Rt7Yu2Io9Ap6Sd1Fg4Hj
IMAGE_GEN_DB_HOST=image_generator_db
IMAGE_GEN_DB_PORT=5432

# Resource Manager Database
RESOURCE_DB_NAME=resource_db_prod
RESOURCE_DB_USER=resource_admin
RESOURCE_DB_PASSWORD=ProdResource2024#Vs7Fh4Jm9Kn1Lp8Qz3Xc6Vb2Nt5Gr
RESOURCE_DB_HOST=resource_db
RESOURCE_DB_PORT=5432

# Classifier Database
CLASSIFIER_DB_NAME=classifier_db_prod
CLASSIFIER_DB_USER=classifier_admin
CLASSIFIER_DB_PASSWORD=ProdClassifier2024#Z2Xc5Vb8Nm6Kh9Jg1Tp4Yr7Ew3Qu
CLASSIFIER_DB_HOST=classifier_db
CLASSIFIER_DB_PORT=5432

# Analysis Database
ANALYSIS_DB_NAME=analysis_db_prod
ANALYSIS_DB_USER=analysis_admin
ANALYSIS_DB_PASSWORD=ProdAnalysis2024#Tl9Yu4Io8Pa3Sd6Fg1Hj5Km2Zx7Cv
ANALYSIS_DB_HOST=analysis_db
ANALYSIS_DB_PORT=5432

# RAG Database
RAG_DB_NAME=rag_db_prod
RAG_DB_USER=rag_admin
RAG_DB_PASSWORD=ProdRag2024#Hj6Km2Lz1Xc8Vb3Nm9Qw5Er7Ty4Ui
RAG_DB_HOST=rag_db
RAG_DB_PORT=5432

# Learning Database
LEARNING_DB_NAME=learning_db_prod
LEARNING_DB_USER=learning_admin
LEARNING_DB_PASSWORD=ProdLearning2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx
SERVICE_DB_NAME=learning_db_prod
SERVICE_DB_USER=learning_admin
SERVICE_DB_PASSWORD=ProdLearning2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx
SERVICE_DB_HOST=learning_db
SERVICE_DB_PORT=5432

# LLM Service Database
LLM_DB_NAME=llm_service_db_prod
LLM_DB_USER=llm_admin
LLM_DB_PASSWORD=ProdLLM2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx
LLM_DB_HOST=llm_service_db
LLM_DB_PORT=5432

# Cost Monitoring Database
COST_MONITORING_DB_NAME=cost_monitoring_db_prod
COST_MONITORING_DB_USER=cost_admin
COST_MONITORING_DB_PASSWORD=ProdCost2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx
COST_DB_HOST=cost_monitoring_db
COST_DB_PORT=5432

# =============================================================================
# RABBITMQ & CELERY CONFIGURATION - PRODUCTION
# =============================================================================
RABBITMQ_DEFAULT_USER=prod_admin
RABBITMQ_DEFAULT_PASS=ProdRabbitMQ2024#Sd9Fg2Hj5Kl8Zx1Cv4Vb7Nm0Qt3Wr
CELERY_BROKER_URL=amqp://prod_admin:ProdRabbitMQ2024#Sd9Fg2Hj5Kl8Zx1Cv4Vb7Nm0Qt3Wr@rabbitmq:5672//

# =============================================================================
# REDIS CONFIGURATION - PRODUCTION
# =============================================================================
REDIS_URL=redis://redis:6379/0

# =============================================================================
# AUTHENTICATION & JWT CONFIGURATION - PRODUCTION
# =============================================================================
JWT_SECRET_KEY=prod-jwt-secret-shared-between-services-ultra-secure-2024
ACCESS_TOKEN_LIFETIME_DAYS=1
REFRESH_TOKEN_LIFETIME_DAYS=7
INTERNAL_API_SECRET=prod-internal-api-secret-ultra-secure-2024-shared

# =============================================================================
# SOCIAL AUTH CONFIGURATION - PRODUCTION
# =============================================================================
SOCIAL_AUTH_GOOGLE_ENABLED=true
SOCIAL_AUTH_GOOGLE_CLIENT_ID=876325805414-o2uroeic6t6alt9cuauk4nojh7n1mt55.apps.googleusercontent.com
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET=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

SOCIAL_AUTH_APPLE_ENABLED=false
SOCIAL_AUTH_APPLE_CLIENT_ID=your.apple.client.id
SOCIAL_AUTH_APPLE_TEAM_ID=your-apple-team-id
SOCIAL_AUTH_APPLE_KEY_ID=your-apple-key-id
SOCIAL_AUTH_APPLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nyour-apple-private-key\n-----END PRIVATE KEY-----

SOCIAL_AUTH_GITHUB_ENABLED=false
SOCIAL_AUTH_GITHUB_CLIENT_ID=your-github-client-id
SOCIAL_AUTH_GITHUB_CLIENT_SECRET=your-github-client-secret

# =============================================================================
# SUPABASE CONFIGURATION - PRODUCTION
# =============================================================================
SUPABASE_URL=https://vlhruuvlnupusahxlsjq.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaHJ1dXZsbnVwdXNhaHhsc2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzE4NDEsImV4cCI6MjA2Njg0Nzg0MX0.opJ2mUBAfnVqS5ZSR02MhULeywCchV1yRZ9xa0gCHjo
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaHJ1dXZsbnVwdXNhaHhsc2pxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTI3MTg0MSwiZXhwIjoyMDY2ODQ3ODQxfQ.jC5xqbJ4Ds5deF-Vgxjv1QJqz1ey-ecYggxQSMjXWWE
SUPABASE_JWT_SECRET=jUj/DOzLViwMZZhRFD1yEshYAsfhxW0xSmhbGkjTme3tPa0ba+Xor73RwyUt6KqBKlMi7ODXEv73zu3i67MdBA==

# =============================================================================
# RAG SERVICE CONFIGURATION - PRODUCTION
# =============================================================================
RAG_UPLOADS_ROOT=/app/rag_uploads
RAG_EMBEDDINGS_ROOT=/app/rag_embeddings
RAG_MAX_CHUNK_SIZE=1000
RAG_CHUNK_OVERLAP=200
RAG_TOP_K_RESULTS=5
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_DIMENSION=1536

# =============================================================================
# LLM SERVICE CONFIGURATION - PRODUCTION
# =============================================================================
OLLAMA_API_BASE_URL=http://ollama_server:11434

# =============================================================================
# LEARNING SERVICE CONFIGURATION - PRODUCTION
# =============================================================================
DEFAULT_LESSON_LENGTH=15
DEFAULT_QUIZ_QUESTIONS=5
MAX_LESSON_APPROFONDIMENTI=4
OPENAI_API_KEY_FILE=/run/secrets/openai_api_key_secret

# =============================================================================
# COST MONITORING CONFIGURATION - PRODUCTION
# =============================================================================
COST_MONITORING_SERVICE_URL=http://cost_monitoring_service:8000
EUROS_TO_CREDITS_RATIO=1000
DEFAULT_USER_CREDITS=5000
OPENAI_BASE_URL=https://api.openai.com/v1

# =============================================================================
# FILE UPLOAD CONFIGURATION - PRODUCTION
# =============================================================================
FILE_UPLOAD_MAX_MEMORY_SIZE=10485760
DATA_UPLOAD_MAX_MEMORY_SIZE=10485760
MAX_PROFILE_PICTURE_SIZE=5242880
ALLOWED_IMAGE_FORMATS=jpg,jpeg,png,gif

# =============================================================================
# USER SERVICE CONFIGURATION - PRODUCTION
# =============================================================================
DEFAULT_USER_STATUS=active

# =============================================================================
# TENSORFLOW CONFIGURATION - PRODUCTION
# =============================================================================
TF_CPP_MIN_LOG_LEVEL=3

# =============================================================================
# INTERNAL SERVICE URLS - PRODUCTION
# =============================================================================
RESOURCE_MANAGER_INTERNAL_URL=http://resource_manager_service:8000
RAG_SERVICE_URL=http://rag_service:8000

# =============================================================================
# STORAGE CONFIGURATION (S3 - Production)
# =============================================================================
USE_S3_STORAGE=true
AWS_ACCESS_KEY_ID=your_production_aws_access_key_id
AWS_SECRET_ACCESS_KEY=your_production_aws_secret_access_key
AWS_STORAGE_BUCKET_NAME=pl-ai-production-bucket
AWS_S3_REGION_NAME=eu-west-1
AWS_S3_CUSTOM_DOMAIN=pl-ai-production-bucket.s3.amazonaws.com
AWS_S3_OBJECT_PARAMETERS={"CacheControl": "max-age=86400"}
AWS_DEFAULT_ACL=private

# =============================================================================
# MEDIA & STATIC FILES - PRODUCTION
# =============================================================================
MEDIA_URL=/media/
STATIC_URL=/static/

# =============================================================================
# DOMAIN CONFIGURATION - PRODUCTION
# =============================================================================
DOMAIN=pl-ai.it
FRONTEND_URL=https://pl-ai.it
BACKEND_URL=https://pl-ai.it/api
FRONTEND_BASE_URL=https://pl-ai.it

# =============================================================================
# CORS SETTINGS (Production)
# =============================================================================
CORS_ALLOWED_ORIGINS=https://pl-ai.it,https://www.pl-ai.it
CORS_ALLOW_CREDENTIALS=true

# =============================================================================
# SSL CONFIGURATION - PRODUCTION
# =============================================================================
LETSENCRYPT_EMAIL=admin@pl-ai.it
SSL_POLICY=Mozilla-Modern

# =============================================================================
# SECURITY SETTINGS - PRODUCTION
# =============================================================================
SECURE_SSL_REDIRECT=true
SECURE_HSTS_SECONDS=31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS=true
SECURE_HSTS_PRELOAD=true
SECURE_CONTENT_TYPE_NOSNIFF=true
SECURE_BROWSER_XSS_FILTER=true
X_FRAME_OPTIONS=DENY

# =============================================================================
# PERFORMANCE & MONITORING - PRODUCTION
# =============================================================================
NGINX_WORKER_PROCESSES=auto
NGINX_WORKER_CONNECTIONS=1024
NGINX_CLIENT_MAX_BODY_SIZE=100M
POSTGRES_SHARED_BUFFERS=256MB
POSTGRES_EFFECTIVE_CACHE_SIZE=1GB

# =============================================================================
# RATE LIMITING - PRODUCTION
# =============================================================================
NGINX_RATE_LIMIT=10r/s
NGINX_BURST_LIMIT=20
DJANGO_RATE_LIMIT_ENABLE=true
API_RATE_LIMIT=100/hour

# =============================================================================
# BACKUP CONFIGURATION - PRODUCTION  
# =============================================================================
BACKUP_ENABLED=true
BACKUP_SCHEDULE=0 2 * * *
BACKUP_RETENTION_DAYS=30
EOF
}

# Setup file environment
setup_env_files() {
    log_info "Checking environment files..."
    
    # Crea .env.dev se non esiste
    if [[ -f ".env.dev" ]]; then
        log_success ".env.dev already exists"
    else
        log_info "Creating .env.dev..."
        create_env_dev_file
        log_success ".env.dev created successfully"
    fi
    
    # Crea .env.prod se non esiste
    if [[ -f ".env.prod" ]]; then
        log_success ".env.prod already exists"
    else
        log_info "Creating .env.prod..."
        create_env_prod_file
        log_success ".env.prod created successfully"
    fi
}

# Genera password sicure personalizzate
customize_passwords() {
    log_info "Generating secure passwords..."
    
    # Development passwords
    local dev_auth_pass=$(generate_password 24)
    local dev_user_pass=$(generate_password 24)
    local dev_chatbot_pass=$(generate_password 24)
    local dev_imagegen_pass=$(generate_password 24)
    local dev_resource_pass=$(generate_password 24)
    local dev_classifier_pass=$(generate_password 24)
    local dev_analysis_pass=$(generate_password 24)
    local dev_rag_pass=$(generate_password 24)
    local dev_learning_pass=$(generate_password 24)
    local dev_llm_pass=$(generate_password 24)
    local dev_cost_pass=$(generate_password 24)
    local dev_rabbitmq_pass=$(generate_password 24)
    local dev_django_secret=$(generate_django_secret)
    local dev_jwt_secret=$(generate_password 32)
    local dev_internal_secret=$(generate_password 32)
    
    # Production passwords (più lunghe)
    local prod_auth_pass=$(generate_password 32)
    local prod_user_pass=$(generate_password 32)
    local prod_chatbot_pass=$(generate_password 32)
    local prod_imagegen_pass=$(generate_password 32)
    local prod_resource_pass=$(generate_password 32)
    local prod_classifier_pass=$(generate_password 32)
    local prod_analysis_pass=$(generate_password 32)
    local prod_rag_pass=$(generate_password 32)
    local prod_learning_pass=$(generate_password 32)
    local prod_llm_pass=$(generate_password 32)
    local prod_cost_pass=$(generate_password 32)
    local prod_rabbitmq_pass=$(generate_password 32)
    local prod_django_secret=$(generate_django_secret)
    local prod_jwt_secret=$(generate_password 48)
    local prod_internal_secret=$(generate_password 48)
    
    # Compatibilità macOS/Linux per sed
    if [[ "$OSTYPE" == "darwin"* ]]; then
        SED_INPLACE="sed -i .bak"
    else
        SED_INPLACE="sed -i"
    fi
    
    # Aggiorna file development
    $SED_INPLACE "s/DevAuth2024!K7mN9pQ3xR8vW2sE/DevAuth2024!$dev_auth_pass/g" .env.dev
    $SED_INPLACE "s/DevUser2024!A4hT6uY9oP1zM5kL/DevUser2024!$dev_user_pass/g" .env.dev
    $SED_INPLACE "s/DevChatbot2024!D3fG7jH2nB9vC6xZ/DevChatbot2024!$dev_chatbot_pass/g" .env.dev
    $SED_INPLACE "s/DevImageGen2024!X8kM4pW7qR3tY5uI/DevImageGen2024!$dev_imagegen_pass/g" .env.dev
    $SED_INPLACE "s/DevResource2024!V2sF9hJ6mK1nL8pQ/DevResource2024!$dev_resource_pass/g" .env.dev
    $SED_INPLACE "s/DevClassifier2024!Z5xC8vB3nM6kH9jG/DevClassifier2024!$dev_classifier_pass/g" .env.dev
    $SED_INPLACE "s/DevAnalysis2024!T4yU7iO0pA3sD6fG/DevAnalysis2024!$dev_analysis_pass/g" .env.dev
    $SED_INPLACE "s/DevRag2024!H9jK2lZ5xC8vB1nM/DevRag2024!$dev_rag_pass/g" .env.dev
    $SED_INPLACE "s/DevLearning2024!Q6wE9rT2yU5iO8pA/DevLearning2024!$dev_learning_pass/g" .env.dev
    $SED_INPLACE "s/DevLLM2024!Q6wE9rT2yU5iO8pA/DevLLM2024!$dev_llm_pass/g" .env.dev
    $SED_INPLACE "s/DevCost2024!Q6wE9rT2yU5iO8pA/DevCost2024!$dev_cost_pass/g" .env.dev
    $SED_INPLACE "s/DevRabbitMQ2024!S3dF6gH9jK2lZ5xC/DevRabbitMQ2024!$dev_rabbitmq_pass/g" .env.dev
    $SED_INPLACE "s/dev-secret-key-x8k3m7p2q5w9r6t4y7u0i3o6p9a2s5d8f1g4h7j0k3l6z9x2c5v8b/$dev_django_secret/g" .env.dev
    $SED_INPLACE "s/dev-jwt-secret-shared-between-services-2024/$dev_jwt_secret/g" .env.dev
    $SED_INPLACE "s/dev-internal-api-secret-2024-shared/$dev_internal_secret/g" .env.dev
    
    # Aggiorna anche Celery URL in development
    $SED_INPLACE "s/DevRabbitMQ2024!S3dF6gH9jK2lZ5xC/DevRabbitMQ2024!$dev_rabbitmq_pass/g" .env.dev
    
    # Aggiorna file production
    $SED_INPLACE "s/ProdAuth2024#Kx9Mn7Pq5Xr2Wv8Sg4Tl6Yh1Uj3Zn/ProdAuth2024#$prod_auth_pass/g" .env.prod
    $SED_INPLACE "s/ProdUser2024#Az8Ht4Uy7Op9Zm1Lk5Pg3Qw6Vb2Nx/ProdUser2024#$prod_user_pass/g" .env.prod
    $SED_INPLACE "s/ProdChatbot2024#Df1Gj5Hm8Nb7Vx3Zc9Kw2Qt6Yr4Eu/ProdChatbot2024#$prod_chatbot_pass/g" .env.prod
    $SED_INPLACE "s/ProdImageGen2024#Xk3Mp8Wq5Rt7Yu2Io9Ap6Sd1Fg4Hj/ProdImageGen2024#$prod_imagegen_pass/g" .env.prod
    $SED_INPLACE "s/ProdResource2024#Vs7Fh4Jm9Kn1Lp8Qz3Xc6Vb2Nt5Gr/ProdResource2024#$prod_resource_pass/g" .env.prod
    $SED_INPLACE "s/ProdClassifier2024#Z2Xc5Vb8Nm6Kh9Jg1Tp4Yr7Ew3Qu/ProdClassifier2024#$prod_classifier_pass/g" .env.prod
    $SED_INPLACE "s/ProdAnalysis2024#Tl9Yu4Io8Pa3Sd6Fg1Hj5Km2Zx7Cv/ProdAnalysis2024#$prod_analysis_pass/g" .env.prod
    $SED_INPLACE "s/ProdRag2024#Hj6Km2Lz1Xc8Vb3Nm9Qw5Er7Ty4Ui/ProdRag2024#$prod_rag_pass/g" .env.prod
    $SED_INPLACE "s/ProdLearning2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx/ProdLearning2024#$prod_learning_pass/g" .env.prod
    $SED_INPLACE "s/ProdLLM2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx/ProdLLM2024#$prod_llm_pass/g" .env.prod
    $SED_INPLACE "s/ProdCost2024#Qw8Er5Ty2Ui9Op3As6Df1Gh4Jk7Zx/ProdCost2024#$prod_cost_pass/g" .env.prod
    $SED_INPLACE "s/ProdRabbitMQ2024#Sd9Fg2Hj5Kl8Zx1Cv4Vb7Nm0Qt3Wr/ProdRabbitMQ2024#$prod_rabbitmq_pass/g" .env.prod
    $SED_INPLACE "s/prod-ultra-secure-key-n8m2k5j9h6g3f0d1s4a7p0q9w8e5r2t7y4u1i6o3p9a8s5d2f7g0h3j6k9l2z5x8c1v4b/$prod_django_secret/g" .env.prod
    $SED_INPLACE "s/prod-jwt-secret-shared-between-services-ultra-secure-2024/$prod_jwt_secret/g" .env.prod
    $SED_INPLACE "s/prod-internal-api-secret-ultra-secure-2024-shared/$prod_internal_secret/g" .env.prod
    
    # Aggiorna anche Celery URL in production
    $SED_INPLACE "s/ProdRabbitMQ2024#Sd9Fg2Hj5Kl8Zx1Cv4Vb7Nm0Qt3Wr/ProdRabbitMQ2024#$prod_rabbitmq_pass/g" .env.prod
    
    # Pulisci file backup su macOS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        rm -f .env.dev.bak .env.prod.bak 2>/dev/null || true
    fi
    
    log_success "Generated unique secure passwords for both environments"
}

# Setup directories secrets
setup_secrets_directories() {
    log_info "Creating secrets directories..."
    
    mkdir -p .secrets/dev
    mkdir -p .secrets/prod
    
    # Imposta permessi sicuri
    chmod 700 .secrets
    chmod 700 .secrets/dev
    chmod 700 .secrets/prod
    
    log_success "Created secrets directories with secure permissions"
}

# Crea file secrets template
create_secrets_templates() {
    log_info "Creating secrets template files..."
    
    # Development secrets
    cat > .secrets/dev/openai_api_key.txt << 'EOF'
# Inserisci qui la tua chiave OpenAI per sviluppo
# Esempio: sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
EOF

    cat > .secrets/dev/anthropic_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Anthropic per sviluppo
# Esempio: sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
EOF

    cat > .secrets/dev/gemini_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Gemini per sviluppo
# Esempio: AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF

    cat > .secrets/dev/stability_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Stability AI per sviluppo
# Esempio: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF

    # Production secrets
    cat > .secrets/prod/openai_api_key.txt << 'EOF'
# Inserisci qui la tua chiave OpenAI per produzione
# Esempio: sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
EOF

    cat > .secrets/prod/anthropic_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Anthropic per produzione
# Esempio: sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
EOF

    cat > .secrets/prod/gemini_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Gemini per produzione
# Esempio: AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF

    cat > .secrets/prod/stability_api_key.txt << 'EOF'
# Inserisci qui la tua chiave Stability AI per produzione
# Esempio: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
EOF

    # Imposta permessi
    chmod 600 .secrets/dev/*.txt
    chmod 600 .secrets/prod/*.txt
    
    log_success "Created secrets template files"
}

# Mostra riepilogo
show_summary() {
    echo -e "\n${GREEN}╔══════════════════════════════════════════════════════════════╗"
    echo -e "║                    SETUP COMPLETATO!                        ║"
    echo -e "╚══════════════════════════════════════════════════════════════╝${NC}\n"
    
    echo -e "${YELLOW}File creati:${NC}"
    echo -e "✅ .env.dev - Configurazione ambiente sviluppo"
    echo -e "✅ .env.prod - Configurazione ambiente produzione"
    echo -e "✅ .secrets/dev/ - Directory secrets sviluppo"
    echo -e "✅ .secrets/prod/ - Directory secrets produzione"
    
    echo -e "\n${YELLOW}PROSSIMI PASSI:${NC}"
    echo -e "1. 🔑 Modifica i file secrets con le tue API keys:"
    echo -e "   nano .secrets/dev/openai_api_key.txt"
    echo -e "   nano .secrets/prod/openai_api_key.txt"
    echo -e "   # Ripeti per tutte le API keys..."
    
    echo -e "\n2. ⚙️ Personalizza ulteriormente i file .env se necessario:"
    echo -e "   nano .env.dev"
    echo -e "   nano .env.prod"
    
    echo -e "\n3. 🌐 Configura i record DNS su IONOS"
    echo -e "   A    @     [IP_SERVER]"
    echo -e "   A    www   [IP_SERVER]"
    echo -e "   A    dev   [IP_SERVER]"
    
    echo -e "\n4. 🔐 Configura SSL:"
    echo -e "   ./ssl-setup.sh dev --staging  # Test"
    echo -e "   ./ssl-setup.sh prod"
    
    echo -e "\n5. 🚀 Deploy:"
    echo -e "   ./deploy.sh dev up --build"
    echo -e "   ./deploy.sh prod up --build"
    
    echo -e "\n${GREEN}Il tuo ambiente è pronto per essere configurato!${NC}"
}

# Menu interattivo
interactive_setup() {
    echo -e "${BLUE}Vuoi procedere con la configurazione automatica?${NC}"
    echo "1. ✅ Sì, configura tutto automaticamente"
    echo "2. 🔧 Sì, ma fammi personalizzare alcuni valori"
    echo "3. ❌ No, esco"
    
    read -p "Scelta: " choice
    
    case $choice in
        1)
            return 0
            ;;
        2)
            echo -e "\n${YELLOW}Configurazione personalizzata:${NC}"
            read -p "Inserisci il tuo dominio principale (default: pl-ai.it): " main_domain
            read -p "Inserisci il tuo dominio di sviluppo (default: dev.pl-ai.it): " dev_domain
            read -p "Inserisci la tua email per SSL (default: admin@pl-ai.it): " ssl_email
            
            # Compatibilità macOS/Linux per sed
            if [[ "$OSTYPE" == "darwin"* ]]; then
                SED_INPLACE="sed -i .bak"
            else
                SED_INPLACE="sed -i"
            fi
            
            # Aggiorna domini se specificati
            if [[ -n "$main_domain" && "$main_domain" != "pl-ai.it" ]]; then
                $SED_INPLACE "s/pl-ai.it/$main_domain/g" .env.prod
            fi
            
            if [[ -n "$dev_domain" && "$dev_domain" != "dev.pl-ai.it" ]]; then
                $SED_INPLACE "s/dev.pl-ai.it/$dev_domain/g" .env.dev
            fi
            
            if [[ -n "$ssl_email" && "$ssl_email" != "admin@pl-ai.it" ]]; then
                eval "$SED_INPLACE \"s/admin@pl-ai.it/$ssl_email/g\" .env.dev .env.prod"
            fi
            
            # Pulisci file backup su macOS
            if [[ "$OSTYPE" == "darwin"* ]]; then
                rm -f .env.dev.bak .env.prod.bak 2>/dev/null || true
            fi
            
            return 0
            ;;
        3)
            log_info "Setup annullato dall'utente"
            exit 0
            ;;
        *)
            log_error "Scelta non valida"
            interactive_setup
            ;;
    esac
}

# Funzione principale
main() {
    # Verifica prerequisiti
    check_prerequisites
    
    # Menu interattivo
    interactive_setup
    
    # Setup file environment
    setup_env_files
    
    # Genera password personalizzate
    customize_passwords
    
    # Setup directories secrets
    setup_secrets_directories
    
    # Crea template secrets
    create_secrets_templates
    
    # Mostra riepilogo
    show_summary
}

# Esegui main
main "$@" 