# Generated by Django 4.2.21 on 2025-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
