# Generated by Django 4.2.23 on 2025-07-21 12:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_remove_chat_user_chat_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('operation_type', models.CharField(help_text="Tipo di operazione (es: 'conversation', 'system_message')", max_length=50)),
                ('service_name', models.CharField(default='chatbot', help_text="Nome del servizio ('chatbot')", max_length=50)),
                ('model_used', models.CharField(help_text='Modello AI utilizzato', max_length=100)),
                ('input_data', models.TextField(blank=True, help_text='Messaggio utente o prompt')),
                ('output_summary', models.TextField(blank=True, help_text='Inizio della risposta AI')),
                ('tokens_consumed', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('response_time_ms', models.PositiveIntegerField(help_text='Tempo di risposta in millisecondi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'service_name'], name='chatbot_api_user_id_517852_idx'), models.Index(fields=['created_at'], name='chatbot_api_created_9a7549_idx')],
            },
        ),
    ]
