# Generated by Django 4.2.23 on 2025-07-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_serviceusagetracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsettings',
            name='subject',
        ),
    ]
