# Generated by Django 4.2.21 on 2025-05-08 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveBigIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='Untitled Model', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('model_path', models.CharField(blank=True, help_text='Relative path to the saved Keras model file (.h5 or .keras)', max_length=512, null=True)),
                ('class_names_path', models.CharField(blank=True, help_text='Relative path to the class names JSON file', max_length=512, null=True)),
                ('class_names', models.JSONField(default=list, help_text='List of class names used during training')),
                ('accuracy', models.FloatField(blank=True, help_text='Training accuracy', null=True)),
                ('loss', models.FloatField(blank=True, help_text='Training loss', null=True)),
                ('training_params', models.JSONField(default=dict, help_text='Parameters used for training (e.g., epochs, batch_size)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_id', 'status'], name='classifier__owner_i_607b68_idx')],
            },
        ),
    ]
