# Generated by Django 4.2.23 on 2025-07-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='resource_manager_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID della risorsa nel Resource Manager Service se caricata', null=True),
        ),
    ]
