# Generated by Django 4.2.20 on 2025-04-18 07:18

from django.db import migrations, models
import generator_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveBigIntegerField(db_index=True, help_text='User ID from the authentication service')),
                ('name', models.CharField(blank=True, help_text='Optional user-defined name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional user-defined description')),
                ('prompt', models.TextField(blank=True, help_text='Prompt used for generation')),
                ('style', models.CharField(blank=True, help_text='Style parameter used', max_length=100, null=True)),
                ('model_used', models.CharField(blank=True, help_text='Model used (e.g., dalle, stability)', max_length=50)),
                ('image_file', models.ImageField(help_text='Path to the saved image file relative to MEDIA_ROOT', max_length=500, upload_to=generator_api.models.get_user_image_path)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
