# Generated by Django 4.2.23 on 2025-07-17 08:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, help_text='User ID from the authentication service')),
                ('operation_type', models.CharField(choices=[('text-to-image', 'Text to Image'), ('image-to-image', 'Image to Image'), ('prompt-enhancement', 'Prompt Enhancement')], help_text='Type of operation performed', max_length=20)),
                ('model_used', models.CharField(choices=[('dalle-2', 'DALL-E 2'), ('dalle-3', 'DALL-E 3'), ('dalle-3-hd', 'DALL-E 3 HD'), ('gpt-image-1', 'GPT-Image-1'), ('stability', 'Stability AI'), ('gpt-4', 'GPT-4 (prompt enhancement)')], help_text='AI model used for the operation', max_length=50)),
                ('prompt', models.TextField(help_text='Prompt used for generation')),
                ('quality', models.CharField(blank=True, help_text='Quality setting used (standard, hd, etc.)', max_length=20, null=True)),
                ('aspect_ratio', models.CharField(blank=True, help_text='Aspect ratio used (1:1, 16:9, etc.)', max_length=10, null=True)),
                ('tokens_consumed', models.IntegerField(default=0, help_text='Number of tokens consumed')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost in USD', max_digits=10)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost in EUR', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the operation was successful')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='generator_a_user_id_e0296c_idx'), models.Index(fields=['user_id', 'operation_type'], name='generator_a_user_id_3f9f62_idx'), models.Index(fields=['user_id', 'model_used'], name='generator_a_user_id_1b67a7_idx')],
            },
        ),
    ]
