# Generated by Django 4.2.23 on 2025-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (max 5MB)', null=True, upload_to='profile_images/'),
        ),
    ]
