# Generated by Django 4.2.7 on 2025-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='depth_level',
            field=models.IntegerField(default=3, help_text='Livello di approfondimento (1-5)'),
        ),
    ]
