# Generated by Django 4.2.7 on 2025-07-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0003_add_flashcard_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardreview',
            name='flashcard',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='FlashcardReview',
        ),
    ]
