# Generated by Django 4.2.7 on 2025-07-24 10:59

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0004_remove_flashcardreview_flashcard_delete_flashcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.PositiveBigIntegerField(db_index=True, help_text='ID utente dal servizio auth')),
                ('operation_type', models.CharField(help_text='Tipo di operazione (lesson_generation, quiz_generation, approfondimenti_generation)', max_length=50)),
                ('service_name', models.CharField(default='learning', help_text='Nome del servizio', max_length=50)),
                ('model_used', models.CharField(help_text='Modello AI utilizzato', max_length=100)),
                ('input_data', models.TextField(blank=True, help_text='Dati di input (topic, prompt, etc.)')),
                ('output_summary', models.TextField(blank=True, help_text="Riassunto dell'output generato")),
                ('tokens_consumed', models.PositiveIntegerField(default=0, help_text='Token utilizzati')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo in USD', max_digits=10)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo in EUR', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text="Se l'operazione è riuscita. Le chiamate fallite non vengono addebitate.")),
                ('response_time_ms', models.PositiveIntegerField(help_text='Tempo di risposta in millisecondi')),
            ],
            options={
                'verbose_name': 'Tracking Utilizzo Servizio',
                'verbose_name_plural': 'Tracking Utilizzi Servizi',
                'db_table': 'learning_service_usage_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'service_name'], name='learning_se_user_id_f01a5a_idx'), models.Index(fields=['user_id', 'success'], name='learning_se_user_id_644054_idx'), models.Index(fields=['created_at'], name='learning_se_created_27d0ef_idx'), models.Index(fields=['operation_type'], name='learning_se_operati_636aee_idx')],
            },
        ),
    ]
