# Generated by Django 4.2.21 on 2025-05-13 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveBigIntegerField(db_index=True, help_text='User ID from the auth service')),
                ('name', models.CharField(default='My Chatbot', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='You are a helpful AI assistant.', help_text="Base instructions defining the chatbot's persona and behavior.")),
                ('llm_model_name', models.CharField(default='gpt-4o-mini', help_text='Specific LLM engine to use (e.g., gpt-4o-mini, claude-3-haiku, gemini-1.5-flash).', max_length=100)),
                ('grade_level', models.CharField(blank=True, help_text="E.g., 'Scuola Primaria', 'Università'", max_length=50, null=True)),
                ('mode', models.CharField(blank=True, help_text="E.g., 'interrogazione', 'intervista', 'rag', 'general_chat'", max_length=50, null=True)),
                ('subject', models.CharField(blank=True, help_text="E.g., 'Storia', 'Scienze'", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveBigIntegerField(db_index=True, help_text="User ID from the auth service, matches profile's owner")),
                ('title', models.CharField(blank=True, help_text='Optional title, e.g., first user message snippet', max_length=200, null=True)),
                ('active_rag_resource_ids', models.JSONField(blank=True, default=list, help_text='List of resource IDs used for RAG in this conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat_api.chatbotprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('llm_model_used', models.CharField(blank=True, help_text='LLM model that generated this assistant message', max_length=100, null=True)),
                ('token_info', models.JSONField(blank=True, help_text="Token usage: {'input': N, 'output': M, 'total': T}", null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_api.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner_id', 'profile'], name='chat_api_co_owner_i_514b3b_idx'),
        ),
    ]
