# Generated by Django 4.2.23 on 2025-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Nome del tag (es. 'RAG', 'Dataset', 'Image')", max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Colore esadecimale per la visualizzazione del tag', max_length=7)),
                ('description', models.CharField(blank=True, help_text='Descrizione del tag', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tag associati a questa risorsa', related_name='resources', to='resources_api.tag'),
        ),
    ]
