# Generated by Django 4.2.7 on 2025-06-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(default='global', max_length=50)),
                ('message_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rag_api.ragknowledgebase')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='RAGChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_user', models.BooleanField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag_api.ragchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['user_id', 'knowledge_base'], name='rag_api_rag_user_id_ff15b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['user_id', 'mode'], name='rag_api_rag_user_id_7d67bc_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['last_activity'], name='rag_api_rag_last_ac_f05be3_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='rag_api_rag_session_583a60_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['session', 'is_user'], name='rag_api_rag_session_752f8f_idx'),
        ),
    ]
