# Generated by Django 4.2.7 on 2025-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0002_add_resource_id'),
        ('rag_api', '0002_ragchatsession_ragchatmessage_and_more'),
    ]

    operations = [
    ]
