# Generated by Django 4.2.21 on 2025-05-12 16:24

import analysis_api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveBigIntegerField(db_index=True)),
                ('resource_id', models.PositiveBigIntegerField(blank=True, help_text='ID of the resource in ResourceManager', null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(blank=True, choices=[('regression', 'Regression'), ('classification', 'Classification')], max_length=50, null=True)),
                ('selected_algorithm_key', models.CharField(blank=True, max_length=100, null=True)),
                ('input_parameters', models.JSONField(default=dict, help_text='Features, target, algorithm params, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Metrics and other textual results', null=True)),
                ('plot_data', models.JSONField(blank=True, default=dict, help_text='Data prepared for frontend plotting', null=True)),
                ('model_path', models.FileField(blank=True, help_text='Path to the saved trained model (if any)', max_length=512, null=True, upload_to=analysis_api.models.analysis_upload_path)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_started_at', models.DateTimeField(blank=True, null=True)),
                ('job_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
