# Generated by Django 4.2.23 on 2025-07-17 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_api', '0002_syntheticdatasetjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('operation_type', models.CharField(help_text="Tipo di operazione (es: 'algorithm_suggestion', 'data_analysis', 'prediction', 'synthetic_dataset')", max_length=50)),
                ('service_name', models.CharField(default='analysis', help_text='Nome del servizio', max_length=50)),
                ('model_used', models.CharField(help_text='Modello AI utilizzato', max_length=100)),
                ('input_data', models.TextField(blank=True, help_text='Dati di input (dataset info, query, etc.)')),
                ('output_summary', models.TextField(blank=True, help_text="Riassunto dell'output")),
                ('tokens_consumed', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('response_time_ms', models.PositiveIntegerField(help_text='Tempo di risposta in millisecondi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Usage Tracking',
                'verbose_name_plural': 'Service Usage Tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'service_name'], name='analysis_ap_user_id_3fc5f3_idx'), models.Index(fields=['created_at'], name='analysis_ap_created_3a1ca7_idx')],
            },
        ),
    ]
