# Generated by Django 4.2.23 on 2025-07-17 13:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_api', '0003_add_service_usage_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, help_text='User ID from the authentication service')),
                ('operation_type', models.CharField(choices=[('algorithm-suggestion', 'Algorithm Suggestion'), ('data-analysis', 'Data Analysis'), ('instance-prediction', 'Instance Prediction'), ('synthetic-dataset', 'Synthetic Dataset Generation')], help_text='Type of operation performed', max_length=30)),
                ('model_used', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-3-sonnet', 'Claude 3 Sonnet'), ('custom-ml', 'Custom ML Model'), ('scikit-learn', 'Scikit-learn')], help_text='AI model used for the operation', max_length=50)),
                ('input_data', models.TextField(help_text='Input data used (prompt, dataset info, etc.)')),
                ('output_summary', models.TextField(blank=True, help_text='Summary of the output generated', null=True)),
                ('task_type', models.CharField(blank=True, help_text='Type of ML task (regression, classification, etc.)', max_length=20, null=True)),
                ('algorithm_used', models.CharField(blank=True, help_text='ML algorithm used in the analysis', max_length=50, null=True)),
                ('tokens_consumed', models.IntegerField(default=0, help_text='Number of tokens consumed')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost in USD', max_digits=10)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost in EUR', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the operation was successful')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceUsageTracking',
        ),
        migrations.AddIndex(
            model_name='analysisusagetracking',
            index=models.Index(fields=['user_id', 'created_at'], name='analysis_ap_user_id_b83e54_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisusagetracking',
            index=models.Index(fields=['user_id', 'operation_type'], name='analysis_ap_user_id_942ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisusagetracking',
            index=models.Index(fields=['user_id', 'model_used'], name='analysis_ap_user_id_96b457_idx'),
        ),
    ]
